### ISSUE TITLE
imitate_mj.py KeyError: "Unable to open object (object 'obs_B_T_Do' doesn't exist)" for Cartpole

### ISSUE THREAD

**Issue by ghost** [Santara/RAIL#1]
Hi Santara,

  I tried your code imitate_mj.py for Cartpole (CartPole-v0.h5), but I got this:

  (object 'obs_B_T_Do' doesn't exist)" 

  File "imitate_mj.py", line 457, in <module>
    main()
  File "imitate_mj.py", line 210, in main
    len_filter_threshold=args.expert_traj_filt_percentile_threshold)
  File "imitate_mj.py", line 22, in load_dataset
    full_dset_size = f['obs_B_T_Do'].shape[0] # full dataset size
  KeyError: "Unable to open object (object 'obs_B_T_Do' doesn't exist)"

   Thanks!

**Comment by Santara** [comment]
Thanks for pointing this out. The reason for the error is that the h5 files in `classic/` and `modern/` are mere placeholders. We did not upload their contents because we didn't want our repo to be too heavy. You need to download the trained policies from the original GAIL repo of OpenAI: https://github.com/openai/imitation/tree/master/expert_policies

**Comment by ghost** [comment]
Thanks @Santara for your help. I got the file and ran this line:
python imitate_mj.py --mode ga --data classic/CartPole-v0.h5 --limit_trajs 10 --data_subsamp_freq 10 --env_name CartPole-v0 --log training_logs/CartPole/ga_iter_301_CVaR_lambda_0.75.h5 --max_iter 301 --useCVaR --CVaR_Lambda_not_trainable --CVaR_Lambda_val_if_not_trainable 0.75 --CVaR_lr 0.01 --CVaR_alpha 0.9

I got the same error message:

TRAINING RAIL 
{
  "mode":"ga",
  "data":"classic/CartPole-v0.h5",
  "resume_training":false,
  "checkpoint":null,
  "limit_trajs":10,
  "data_subsamp_freq":10,
  "env_name":"CartPole-v0",
  "max_traj_len":null,
  "policy_hidden_spec":"[{\"type\": \"fc\", \"n\": 100}, {\"type\": \"nonlin\", \"func\": \"tanh\"}, {\"type\": \"fc\", \"n\": 100}, {\"type\": \"nonlin\", \"func\": \"tanh\"}]",
  "tiny_policy":false,
  "obsnorm_mode":"expertdata",
  "bclone_lr":0.001,
  "bclone_batch_size":128,
  "bclone_eval_ntrajs":20,
  "bclone_eval_freq":1000,
  "bclone_train_frac":0.7,
  "discount":0.995,
  "lam":0.97,
  "max_iter":301,
  "policy_max_kl":0.01,
  "policy_cg_damping":0.1,
  "no_vf":0,
  "vf_max_kl":0.01,
  "vf_cg_damping":0.1,
  "policy_ent_reg":0.0,
  "reward_type":"nn",
  "reward_max_kl":0.01,
  "reward_lr":0.01,
  "reward_steps":1,
  "reward_ent_reg_weight":0.001,
  "reward_include_time":0,
  "sim_batch_size":null,
  "min_total_sa":50000,
  "favor_zero_expert_reward":0,
  "print_freq":1,
  "save_freq":20,
  "plot_freq":0,
  "log":"training_logs/CartPole/ga_iter_301_CVaR_lambda_0.75.h5",
  "useCVaR":true,
  "CVaR_alpha":0.9,
  "CVaR_beta":0.0,
  "CVaR_lr":0.01,
  "disc_CVaR_weight":1.0,
  "CVaR_Lambda_not_trainable":false,
  "CVaR_Lambda_val_if_not_trainable":0.75,
  "use_expert_traj_filtering":false,
  "expert_traj_filt_percentile_threshold":20,
  "use_additiveStatePrior":false,
  "additiveStatePrior_weight":1.0,
  "n_gmm_components":5,
  "cov_type_gmm":"diag",
  "familiarity_alpha":10000000,
  "familiarity_beta":100,
  "kickThreshold_percentile":100.0,
  "appendFlag":false
}


========== Policy network specifications loaded ===========


Gym version: 0.12.1
MDP observation space, action space sizes: 4, 1



========== MDP initialized ===========


Loading feedforward net specification
[
  {
    "type": "fc",
    "n": 100
  },
  {
    "type": "nonlin",
    "func": "tanh"
  },
  {
    "type": "fc",
    "n": 100
  },
  {
    "type": "nonlin",
    "func": "tanh"
  }
]
Affine(in=4, out=100)
Nonlinearity(func=tanh)
Affine(in=100, out=100)
Nonlinearity(func=tanh)
Affine(in=100, out=2)
Policy architecture
- /GibbsPolicy/hidden/FeedforwardNet/layer_0/AffineLayer/W (400 parameters)
- /GibbsPolicy/hidden/FeedforwardNet/layer_0/AffineLayer/b (100 parameters)
- /GibbsPolicy/hidden/FeedforwardNet/layer_2/AffineLayer/W (10000 parameters)
- /GibbsPolicy/hidden/FeedforwardNet/layer_2/AffineLayer/b (100 parameters)
- /GibbsPolicy/out/AffineLayer/W (200 parameters)
- /GibbsPolicy/out/AffineLayer/b (2 parameters)
Total: 10802 parameters


========== Policy initialized ===========


Traceback (most recent call last):
  File "imitate_mj.py", line 457, in <module>
    main()
  File "imitate_mj.py", line 210, in main
    len_filter_threshold=args.expert_traj_filt_percentile_threshold)
  File "imitate_mj.py", line 22, in load_dataset
    full_dset_size = f['obs_B_T_Do'].shape[0] # full dataset size
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\_hl\group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'obs_B_T_Do' doesn't exist)"
